### ISSUE TITLE
'Invalid time value' when gathering JUnit results 

### ISSUE THREAD

**Issue by mordka** [linguahouse/meteor-mocha-phantomjs-junit#1]
I get this error both locally and in Circle CI.

```
RangeError: Invalid time value
```

![image](https://cloud.githubusercontent.com/assets/3659502/15719079/232a505e-2826-11e6-92c1-c325133a749e.png)

Here are the `stats` JSON:

```
"stats": {
   "suites": 4,
   "tests": 9,
   "passes": 6,
   "pending": 3,
   "failures": 0,
   "start": "2016-06-01T11:55:54.440Z",
   "end": "2016-06-01T11:55:57.947Z",
   "duration": 3507
 }
```

The command used:

`SERVER_TEST_REPORTER=junit CLIENT_TEST_REPORTER=json meteor test --full-app --once --driver-package linguahouse:mocha-phantomjs-junit --settings settings-test.json`

**Comment by javascriptlove** [comment]
Hello @mordka 
Thanks for a report, apparently i didn't test pending tasks... so i made some changes including other bugs i found myself too and they will appear in atmosphere soon. I will close the issue, but if you happen to find other bugs - feel free to reopen or make a new issue if it's not related.

Thanks
