### ISSUE TITLE
 Error: invalid reporter "json"

### ISSUE THREAD

**Issue by jeffryan** [linguahouse/meteor-mocha-phantomjs-junit#2]
I am trying to send both client and server tests to an xml result file. 

As mentioned in the readme I specified a client test reporter of json and invoke my test as follows:

SERVER_TEST_REPORTER=junit CLIENT_TEST_REPORTER=json MOCHA_FILE=./unit-test-reports.xml meteor test-packages --once --driver-package=linguahouse:mocha-phantomjs-junit mypkg

The server tests run fine but I get an error when the client tests run indicating json is not a valid reporter:

```
[[[[[ Tests ]]]]]                             
=> Started proxy.                             
=> Started MongoDB.                           
W20161010-12:50:28.362(-5)? (STDERR) Debugger listening on port 47977
I20161010-12:50:30.533(-5)? 
I20161010-12:50:30.534(-5)? --------------------------------
I20161010-12:50:30.535(-5)? ----- RUNNING SERVER TESTS -----
I20161010-12:50:30.535(-5)? --------------------------------
I20161010-12:50:30.535(-5)? 
I20161010-12:50:30.536(-5)? Mocha: Using JUnit reporter
I20161010-12:50:30.537(-5)? 
I20161010-12:50:30.537(-5)? --------------------------------
I20161010-12:50:30.537(-5)? ----- RUNNING CLIENT TESTS -----
I20161010-12:50:30.537(-5)? --------------------------------
I20161010-12:50:30.537(-5)? 
=> Started your app.

=> App running at: http://localhost:3000/
I20161010-12:50:32.423(-5)? "json" reporter not found
I20161010-12:50:32.424(-5)? Error: invalid reporter "json"

```

Note I am trying to test a package and thus I am pulling this package in through our packages onTest code.

```
Package.onTest(function (api) {
    ...
    api.use('linguahouse:mocha-phantomjs-junit', ['client', 'server']);

```

I also tried adding the package directly to the outer application but got the same results.

Do I need to include another package to pick up the json reporter?

**Comment by bkuster** [comment]
+1

**Comment by javascriptlove** [comment]
Hello, first of all, thanks for trying out the package and sorry for such a late response, we have lots of other stuff in priority.

I think you don't have to explicitly `use` this package, this won't make any sense. Rather, you have to provide it as a `--driver-package` option, something like this:

```
SERVER_TEST_REPORTER=junit CLIENT_TEST_REPORTER=json meteor test-packages --once --driver-package linguahouse:mocha-phantomjs-junit ./packages/dummy-package/
```

We still use Meteor as a "base" for testing, which makes sure the correct driver package is used to run the tests.
